Refactor of ACL storage logic
- The run-consul script will now source a specific script file based on the value given by the new '--acl-storage-type' command line argument. This allows for easier addition of new methods of storing ACL tokens based on a set of common interface functions (write_acl_token, read_acl_token).

- An additional check to ensure that the token generated for the agent is not empty has been added, so that the script will properly throw an error and exit if the token cannot be generated.

- The install-consul script has been updated to include copying all '*.sh' files in the 'modules/run-consul' directory, so as to include any new common script files added from here on out.

- The example deployment with ACLs has been updated with the newly added command line arguments for the user data scripts.

- The test for ACL enabled clusters has been corrected so that it expects an empty response to 'consul members' when not passing in an ACL token.

diff --git a/modules/run-consul/run-consul b/modules/run-consul/run-consul
--- a/modules/run-consul/run-consul
+++ b/modules/run-consul/run-consul
@@ -55,7 +55,8 @@ function print_usage {
   echo -e "  --environment\t\tA single environment variable in the key/value pair form 'KEY=\"val\"' to pass to Consul as environment variable when starting it up. Repeat this option for additional variables. Optional."
   echo -e "  --skip-consul-config\tIf this flag is set, don't generate a Consul configuration file. Optional. Default is false."
   echo -e "  --recursor\tThis flag provides address of upstream DNS server that is used to recursively resolve queries if they are not inside the service domain for Consul. Repeat this option for additional variables. Optional."
-  echo -e "  --enable-acl\tThis flag will cause the cluster to bootstrap a root ACL token upon first provision, which is then stored in AWS SSM for other cluster members to retrieve."
+  echo -e "  --enable-acl\tThis flag will cause the cluster to bootstrap a root ACL token upon first provision, which is then stored in a user chosen store for other cluster members to retrieve."
+  echo -e "  --acl-store-type\tThe type of storage to use when persisting the root ACL token. Currently the only supported value is 'ssm'."
   echo
   echo "Options for Consul Autopilot:"
   echo
@@ -102,6 +103,8 @@ function run {
   local server_stabilization_time="$DEFAULT_AUTOPILOT_SERVER_STABILIZATION_TIME"
   local redundancy_zone_tag="$DEFAULT_AUTOPILOT_REDUNDANCY_ZONE_TAG"
   local disable_upgrade_migration="$DEFAULT_AUTOPILOT_DISABLE_UPGRADE_MIGRATION"
+  local enable_acl
+  local acl_storage_type
 
   while [[ $# -gt 0 ]]; do
     local key="$1"
@@ -232,6 +235,11 @@ function run {
       --enable-acl)
         enable_acl="true"
         ;;
+      --acl-storage-type)
+        assert_not_empty "$key" "$2"
+        acl_storage_type="$2"
+        shift
+        ;;
       --recursor)
         assert_not_empty "$key" "$2"
         recursors+=("$2")
@@ -250,6 +258,29 @@ function run {
 
     shift
   done
+
+  if [[ "$enable_acl" == "true" ]]; then
+    if [ -z "$acl_storage_type" ] || [ "$acl_storage_type" == "" ]; then
+      log_error "You must specify an option for the --acl-storage-type parameter when --enable-acl is specified."
+      exit 1
+    fi
+
+    local storage_type_matched="false"
+
+    # Source appropriate storage provider script
+    case "$acl_storage_type" in 
+        'ssm' | 'SSM')
+        storage_type_matched="true"
+        source ${SCRIPT_DIR}/consul-bootstrap-ssm.sh;;
+
+        *)
+        if [ $storage_type_matched="false" ]; then
+            log_error "ACL storage type '${acl_storage_type}' is not supported."
+            exit 1
+        fi;;
+
+    esac
+  fi
 
   if [[ ("$server" == "true" && "$client" == "true") || ("$server" == "false" && "$client" == "false") ]]; then
     log_error "Exactly one of --server or --client must be set."
@@ -342,7 +373,7 @@ function run {
 
     if [[ "$rally_point_hostname" == "$local_hostname" ]]; then
       log_info "Checking if bootstrap token already exists"
-      local -r existing_token=$(read_acl_token $cluster_tag_value "bootstrap" $aws_region "ssm" 1 0 "true")
+      local -r existing_token=$(read_acl_token $cluster_tag_value "bootstrap" $aws_region 1 0 "true")
 
       if [[ "$existing_token" == "" ]] && [ "${server}" == "true" ]; then
         log_info "Generating bootstrap ACL token"
@@ -358,7 +389,7 @@ function run {
     # then we need to read it.
     if [[ -z "$bootstrap_token" ]]; then
       log_info "Acquiring bootstrap token"
-      bootstrap_token=$(read_acl_token $cluster_tag_value "bootstrap" $aws_region "ssm")
+      bootstrap_token=$(read_acl_token $cluster_tag_value "bootstrap" $aws_region)
     fi
 
     local -r consul_major_version=$(get_consul_major_version)
@@ -371,7 +402,7 @@ function run {
     if ([ $consul_major_version -ge 1 ] && ( [ $consul_minor_version -ge 9 ] || ([ $consul_minor_version -eq 8 ] && [ $consul_build_version -ge 1 ]))) || [ $consul_major_version -gt 1 ]; then
       # Generate the agent token using the newer method
       log_info "Creating agent token using -node-idenity"
-      agent_token=$(generate_agent_token $local_hostname $datacenter $bootstrap_token)
+      agent_token=$(generate_agent_token $instance_id $datacenter $bootstrap_token)
     else
       # Generate agent policy dynamically and write it
       log_info "Creating agent policy and token"
@@ -382,8 +413,12 @@ function run {
       agent_token=$(generate_token "$instance_id" "$instance_id agent policy" $bootstrap_token)
     fi
 
-    set_agent_token "$agent_token" "$bootstrap_token"
-
+    if [ -z "$agent_token" ] || [ "$agent_token" == "" ]; then
+      log_error "Unable to acquire agent token. Aborting."
+      exit 1
+    else
+      set_agent_token "$agent_token" "$bootstrap_token"
+    fi
   fi
 }
 
