Add test for consul enterprise installation

diff --git a/modules/install-consul/install-consul b/modules/install-consul/install-consul
--- a/modules/install-consul/install-consul
+++ b/modules/install-consul/install-consul
@@ -334,7 +334,12 @@ function install {
     install_tls_certificates "$path" "$user" "$ca_file_path" "$cert_file_path" "$key_file_path"
   fi
 
-  log_info "Consul install complete!"
+  if command -v consul; then
+    log_info "Consul install complete!";
+  else
+    log_info "Consul was not installed properly.  Aborting.";
+    exit 1;
+  fi
 }
 
 install "$@"
